# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2ray.com/core/app/stats/command/command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2ray.com/core/app/stats/command/command.proto',
  package='v2ray.core.app.stats.command',
  syntax='proto3',
  serialized_options=_b('\n com.v2ray.core.app.stats.commandP\001Z\007command\252\002\034V2Ray.Core.App.Stats.Command'),
  serialized_pb=_b('\n.v2ray.com/core/app/stats/command/command.proto\x12\x1cv2ray.core.app.stats.command\".\n\x0fGetStatsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\"#\n\x04Stat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\"D\n\x10GetStatsResponse\x12\x30\n\x04stat\x18\x01 \x01(\x0b\x32\".v2ray.core.app.stats.command.Stat\"3\n\x11QueryStatsRequest\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\"F\n\x12QueryStatsResponse\x12\x30\n\x04stat\x18\x01 \x03(\x0b\x32\".v2ray.core.app.stats.command.Stat\"\x08\n\x06\x43onfig2\xee\x01\n\x0cStatsService\x12k\n\x08GetStats\x12-.v2ray.core.app.stats.command.GetStatsRequest\x1a..v2ray.core.app.stats.command.GetStatsResponse\"\x00\x12q\n\nQueryStats\x12/.v2ray.core.app.stats.command.QueryStatsRequest\x1a\x30.v2ray.core.app.stats.command.QueryStatsResponse\"\x00\x42L\n com.v2ray.core.app.stats.commandP\x01Z\x07\x63ommand\xaa\x02\x1cV2Ray.Core.App.Stats.Commandb\x06proto3')
)




_GETSTATSREQUEST = _descriptor.Descriptor(
  name='GetStatsRequest',
  full_name='v2ray.core.app.stats.command.GetStatsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='v2ray.core.app.stats.command.GetStatsRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reset', full_name='v2ray.core.app.stats.command.GetStatsRequest.reset', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=126,
)


_STAT = _descriptor.Descriptor(
  name='Stat',
  full_name='v2ray.core.app.stats.command.Stat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='v2ray.core.app.stats.command.Stat.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='v2ray.core.app.stats.command.Stat.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=163,
)


_GETSTATSRESPONSE = _descriptor.Descriptor(
  name='GetStatsResponse',
  full_name='v2ray.core.app.stats.command.GetStatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stat', full_name='v2ray.core.app.stats.command.GetStatsResponse.stat', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=233,
)


_QUERYSTATSREQUEST = _descriptor.Descriptor(
  name='QueryStatsRequest',
  full_name='v2ray.core.app.stats.command.QueryStatsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pattern', full_name='v2ray.core.app.stats.command.QueryStatsRequest.pattern', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reset', full_name='v2ray.core.app.stats.command.QueryStatsRequest.reset', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=286,
)


_QUERYSTATSRESPONSE = _descriptor.Descriptor(
  name='QueryStatsResponse',
  full_name='v2ray.core.app.stats.command.QueryStatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stat', full_name='v2ray.core.app.stats.command.QueryStatsResponse.stat', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=358,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='v2ray.core.app.stats.command.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=368,
)

_GETSTATSRESPONSE.fields_by_name['stat'].message_type = _STAT
_QUERYSTATSRESPONSE.fields_by_name['stat'].message_type = _STAT
DESCRIPTOR.message_types_by_name['GetStatsRequest'] = _GETSTATSREQUEST
DESCRIPTOR.message_types_by_name['Stat'] = _STAT
DESCRIPTOR.message_types_by_name['GetStatsResponse'] = _GETSTATSRESPONSE
DESCRIPTOR.message_types_by_name['QueryStatsRequest'] = _QUERYSTATSREQUEST
DESCRIPTOR.message_types_by_name['QueryStatsResponse'] = _QUERYSTATSRESPONSE
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetStatsRequest = _reflection.GeneratedProtocolMessageType('GetStatsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSTATSREQUEST,
  __module__ = 'v2ray.com.core.app.stats.command.command_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.GetStatsRequest)
  ))
_sym_db.RegisterMessage(GetStatsRequest)

Stat = _reflection.GeneratedProtocolMessageType('Stat', (_message.Message,), dict(
  DESCRIPTOR = _STAT,
  __module__ = 'v2ray.com.core.app.stats.command.command_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.Stat)
  ))
_sym_db.RegisterMessage(Stat)

GetStatsResponse = _reflection.GeneratedProtocolMessageType('GetStatsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSTATSRESPONSE,
  __module__ = 'v2ray.com.core.app.stats.command.command_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.GetStatsResponse)
  ))
_sym_db.RegisterMessage(GetStatsResponse)

QueryStatsRequest = _reflection.GeneratedProtocolMessageType('QueryStatsRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYSTATSREQUEST,
  __module__ = 'v2ray.com.core.app.stats.command.command_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.QueryStatsRequest)
  ))
_sym_db.RegisterMessage(QueryStatsRequest)

QueryStatsResponse = _reflection.GeneratedProtocolMessageType('QueryStatsResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYSTATSRESPONSE,
  __module__ = 'v2ray.com.core.app.stats.command.command_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.QueryStatsResponse)
  ))
_sym_db.RegisterMessage(QueryStatsResponse)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'v2ray.com.core.app.stats.command.command_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.app.stats.command.Config)
  ))
_sym_db.RegisterMessage(Config)


DESCRIPTOR._options = None

_STATSSERVICE = _descriptor.ServiceDescriptor(
  name='StatsService',
  full_name='v2ray.core.app.stats.command.StatsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=371,
  serialized_end=609,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStats',
    full_name='v2ray.core.app.stats.command.StatsService.GetStats',
    index=0,
    containing_service=None,
    input_type=_GETSTATSREQUEST,
    output_type=_GETSTATSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='QueryStats',
    full_name='v2ray.core.app.stats.command.StatsService.QueryStats',
    index=1,
    containing_service=None,
    input_type=_QUERYSTATSREQUEST,
    output_type=_QUERYSTATSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATSSERVICE)

DESCRIPTOR.services_by_name['StatsService'] = _STATSSERVICE

# @@protoc_insertion_point(module_scope)
