# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2ray.com/core/proxy/shadowsocks/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v2ray.com.core.common.net import network_pb2 as v2ray_dot_com_dot_core_dot_common_dot_net_dot_network__pb2
from v2ray.com.core.common.protocol import user_pb2 as v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_user__pb2
from v2ray.com.core.common.protocol import server_spec_pb2 as v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_server__spec__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2ray.com/core/proxy/shadowsocks/config.proto',
  package='v2ray.core.proxy.shadowsocks',
  syntax='proto3',
  serialized_options=_b('\n com.v2ray.core.proxy.shadowsocksP\001Z\013shadowsocks\252\002\034V2Ray.Core.Proxy.Shadowsocks'),
  serialized_pb=_b('\n-v2ray.com/core/proxy/shadowsocks/config.proto\x12\x1cv2ray.core.proxy.shadowsocks\x1a\'v2ray.com/core/common/net/network.proto\x1a)v2ray.com/core/common/protocol/user.proto\x1a\x30v2ray.com/core/common/protocol/server_spec.proto\"\xce\x01\n\x07\x41\x63\x63ount\x12\x10\n\x08password\x18\x01 \x01(\t\x12=\n\x0b\x63ipher_type\x18\x02 \x01(\x0e\x32(.v2ray.core.proxy.shadowsocks.CipherType\x12>\n\x03ota\x18\x03 \x01(\x0e\x32\x31.v2ray.core.proxy.shadowsocks.Account.OneTimeAuth\"2\n\x0bOneTimeAuth\x12\x08\n\x04\x41uto\x10\x00\x12\x0c\n\x08\x44isabled\x10\x01\x12\x0b\n\x07\x45nabled\x10\x02\"\x88\x01\n\x0cServerConfig\x12\x17\n\x0budp_enabled\x18\x01 \x01(\x08\x42\x02\x18\x01\x12.\n\x04user\x18\x02 \x01(\x0b\x32 .v2ray.core.common.protocol.User\x12/\n\x07network\x18\x03 \x03(\x0e\x32\x1e.v2ray.core.common.net.Network\"J\n\x0c\x43lientConfig\x12:\n\x06server\x18\x01 \x03(\x0b\x32*.v2ray.core.common.protocol.ServerEndpoint*\x9f\x01\n\nCipherType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0b\x41\x45S_128_CFB\x10\x01\x12\x0f\n\x0b\x41\x45S_256_CFB\x10\x02\x12\x0c\n\x08\x43HACHA20\x10\x03\x12\x11\n\rCHACHA20_IETF\x10\x04\x12\x0f\n\x0b\x41\x45S_128_GCM\x10\x05\x12\x0f\n\x0b\x41\x45S_256_GCM\x10\x06\x12\x15\n\x11\x43HACHA20_POLY1305\x10\x07\x12\x08\n\x04NONE\x10\x08\x42P\n com.v2ray.core.proxy.shadowsocksP\x01Z\x0bshadowsocks\xaa\x02\x1cV2Ray.Core.Proxy.Shadowsocksb\x06proto3')
  ,
  dependencies=[v2ray_dot_com_dot_core_dot_common_dot_net_dot_network__pb2.DESCRIPTOR,v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_user__pb2.DESCRIPTOR,v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_server__spec__pb2.DESCRIPTOR,])

_CIPHERTYPE = _descriptor.EnumDescriptor(
  name='CipherType',
  full_name='v2ray.core.proxy.shadowsocks.CipherType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AES_128_CFB', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AES_256_CFB', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHACHA20', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHACHA20_IETF', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AES_128_GCM', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AES_256_GCM', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHACHA20_POLY1305', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NONE', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=638,
  serialized_end=797,
)
_sym_db.RegisterEnumDescriptor(_CIPHERTYPE)

CipherType = enum_type_wrapper.EnumTypeWrapper(_CIPHERTYPE)
UNKNOWN = 0
AES_128_CFB = 1
AES_256_CFB = 2
CHACHA20 = 3
CHACHA20_IETF = 4
AES_128_GCM = 5
AES_256_GCM = 6
CHACHA20_POLY1305 = 7
NONE = 8


_ACCOUNT_ONETIMEAUTH = _descriptor.EnumDescriptor(
  name='OneTimeAuth',
  full_name='v2ray.core.proxy.shadowsocks.Account.OneTimeAuth',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Auto', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Disabled', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enabled', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=370,
  serialized_end=420,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNT_ONETIMEAUTH)


_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='v2ray.core.proxy.shadowsocks.Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='password', full_name='v2ray.core.proxy.shadowsocks.Account.password', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cipher_type', full_name='v2ray.core.proxy.shadowsocks.Account.cipher_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ota', full_name='v2ray.core.proxy.shadowsocks.Account.ota', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACCOUNT_ONETIMEAUTH,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=420,
)


_SERVERCONFIG = _descriptor.Descriptor(
  name='ServerConfig',
  full_name='v2ray.core.proxy.shadowsocks.ServerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='udp_enabled', full_name='v2ray.core.proxy.shadowsocks.ServerConfig.udp_enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='v2ray.core.proxy.shadowsocks.ServerConfig.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network', full_name='v2ray.core.proxy.shadowsocks.ServerConfig.network', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=559,
)


_CLIENTCONFIG = _descriptor.Descriptor(
  name='ClientConfig',
  full_name='v2ray.core.proxy.shadowsocks.ClientConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server', full_name='v2ray.core.proxy.shadowsocks.ClientConfig.server', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=635,
)

_ACCOUNT.fields_by_name['cipher_type'].enum_type = _CIPHERTYPE
_ACCOUNT.fields_by_name['ota'].enum_type = _ACCOUNT_ONETIMEAUTH
_ACCOUNT_ONETIMEAUTH.containing_type = _ACCOUNT
_SERVERCONFIG.fields_by_name['user'].message_type = v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_user__pb2._USER
_SERVERCONFIG.fields_by_name['network'].enum_type = v2ray_dot_com_dot_core_dot_common_dot_net_dot_network__pb2._NETWORK
_CLIENTCONFIG.fields_by_name['server'].message_type = v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_server__spec__pb2._SERVERENDPOINT
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
DESCRIPTOR.message_types_by_name['ServerConfig'] = _SERVERCONFIG
DESCRIPTOR.message_types_by_name['ClientConfig'] = _CLIENTCONFIG
DESCRIPTOR.enum_types_by_name['CipherType'] = _CIPHERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNT,
  __module__ = 'v2ray.com.core.proxy.shadowsocks.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.shadowsocks.Account)
  ))
_sym_db.RegisterMessage(Account)

ServerConfig = _reflection.GeneratedProtocolMessageType('ServerConfig', (_message.Message,), dict(
  DESCRIPTOR = _SERVERCONFIG,
  __module__ = 'v2ray.com.core.proxy.shadowsocks.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.shadowsocks.ServerConfig)
  ))
_sym_db.RegisterMessage(ServerConfig)

ClientConfig = _reflection.GeneratedProtocolMessageType('ClientConfig', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTCONFIG,
  __module__ = 'v2ray.com.core.proxy.shadowsocks.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.shadowsocks.ClientConfig)
  ))
_sym_db.RegisterMessage(ClientConfig)


DESCRIPTOR._options = None
_SERVERCONFIG.fields_by_name['udp_enabled']._options = None
# @@protoc_insertion_point(module_scope)
