# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2ray.com/core/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v2ray.com.core.common.serial import typed_message_pb2 as v2ray_dot_com_dot_core_dot_common_dot_serial_dot_typed__message__pb2
from v2ray.com.core.transport import config_pb2 as v2ray_dot_com_dot_core_dot_transport_dot_config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2ray.com/core/config.proto',
  package='v2ray.core',
  syntax='proto3',
  serialized_options=_b('\n\016com.v2ray.coreP\001Z\004core\252\002\nV2Ray.Core'),
  serialized_pb=_b('\n\x1bv2ray.com/core/config.proto\x12\nv2ray.core\x1a\x30v2ray.com/core/common/serial/typed_message.proto\x1a%v2ray.com/core/transport/config.proto\"\x97\x02\n\x06\x43onfig\x12\x31\n\x07inbound\x18\x01 \x03(\x0b\x32 .v2ray.core.InboundHandlerConfig\x12\x33\n\x08outbound\x18\x02 \x03(\x0b\x32!.v2ray.core.OutboundHandlerConfig\x12\x33\n\x03\x61pp\x18\x04 \x03(\x0b\x32&.v2ray.core.common.serial.TypedMessage\x12/\n\ttransport\x18\x05 \x01(\x0b\x32\x1c.v2ray.core.transport.Config\x12\x39\n\textension\x18\x06 \x03(\x0b\x32&.v2ray.core.common.serial.TypedMessageJ\x04\x08\x03\x10\x04\"\xa6\x01\n\x14InboundHandlerConfig\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x41\n\x11receiver_settings\x18\x02 \x01(\x0b\x32&.v2ray.core.common.serial.TypedMessage\x12>\n\x0eproxy_settings\x18\x03 \x01(\x0b\x32&.v2ray.core.common.serial.TypedMessage\"\xc6\x01\n\x15OutboundHandlerConfig\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12?\n\x0fsender_settings\x18\x02 \x01(\x0b\x32&.v2ray.core.common.serial.TypedMessage\x12>\n\x0eproxy_settings\x18\x03 \x01(\x0b\x32&.v2ray.core.common.serial.TypedMessage\x12\x0e\n\x06\x65xpire\x18\x04 \x01(\x03\x12\x0f\n\x07\x63omment\x18\x05 \x01(\tB%\n\x0e\x63om.v2ray.coreP\x01Z\x04\x63ore\xaa\x02\nV2Ray.Coreb\x06proto3')
  ,
  dependencies=[v2ray_dot_com_dot_core_dot_common_dot_serial_dot_typed__message__pb2.DESCRIPTOR,v2ray_dot_com_dot_core_dot_transport_dot_config__pb2.DESCRIPTOR,])




_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='v2ray.core.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inbound', full_name='v2ray.core.Config.inbound', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outbound', full_name='v2ray.core.Config.outbound', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app', full_name='v2ray.core.Config.app', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transport', full_name='v2ray.core.Config.transport', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extension', full_name='v2ray.core.Config.extension', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=412,
)


_INBOUNDHANDLERCONFIG = _descriptor.Descriptor(
  name='InboundHandlerConfig',
  full_name='v2ray.core.InboundHandlerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='v2ray.core.InboundHandlerConfig.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_settings', full_name='v2ray.core.InboundHandlerConfig.receiver_settings', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proxy_settings', full_name='v2ray.core.InboundHandlerConfig.proxy_settings', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=581,
)


_OUTBOUNDHANDLERCONFIG = _descriptor.Descriptor(
  name='OutboundHandlerConfig',
  full_name='v2ray.core.OutboundHandlerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='v2ray.core.OutboundHandlerConfig.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender_settings', full_name='v2ray.core.OutboundHandlerConfig.sender_settings', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proxy_settings', full_name='v2ray.core.OutboundHandlerConfig.proxy_settings', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expire', full_name='v2ray.core.OutboundHandlerConfig.expire', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='v2ray.core.OutboundHandlerConfig.comment', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=782,
)

_CONFIG.fields_by_name['inbound'].message_type = _INBOUNDHANDLERCONFIG
_CONFIG.fields_by_name['outbound'].message_type = _OUTBOUNDHANDLERCONFIG
_CONFIG.fields_by_name['app'].message_type = v2ray_dot_com_dot_core_dot_common_dot_serial_dot_typed__message__pb2._TYPEDMESSAGE
_CONFIG.fields_by_name['transport'].message_type = v2ray_dot_com_dot_core_dot_transport_dot_config__pb2._CONFIG
_CONFIG.fields_by_name['extension'].message_type = v2ray_dot_com_dot_core_dot_common_dot_serial_dot_typed__message__pb2._TYPEDMESSAGE
_INBOUNDHANDLERCONFIG.fields_by_name['receiver_settings'].message_type = v2ray_dot_com_dot_core_dot_common_dot_serial_dot_typed__message__pb2._TYPEDMESSAGE
_INBOUNDHANDLERCONFIG.fields_by_name['proxy_settings'].message_type = v2ray_dot_com_dot_core_dot_common_dot_serial_dot_typed__message__pb2._TYPEDMESSAGE
_OUTBOUNDHANDLERCONFIG.fields_by_name['sender_settings'].message_type = v2ray_dot_com_dot_core_dot_common_dot_serial_dot_typed__message__pb2._TYPEDMESSAGE
_OUTBOUNDHANDLERCONFIG.fields_by_name['proxy_settings'].message_type = v2ray_dot_com_dot_core_dot_common_dot_serial_dot_typed__message__pb2._TYPEDMESSAGE
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['InboundHandlerConfig'] = _INBOUNDHANDLERCONFIG
DESCRIPTOR.message_types_by_name['OutboundHandlerConfig'] = _OUTBOUNDHANDLERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'v2ray.com.core.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.Config)
  ))
_sym_db.RegisterMessage(Config)

InboundHandlerConfig = _reflection.GeneratedProtocolMessageType('InboundHandlerConfig', (_message.Message,), dict(
  DESCRIPTOR = _INBOUNDHANDLERCONFIG,
  __module__ = 'v2ray.com.core.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.InboundHandlerConfig)
  ))
_sym_db.RegisterMessage(InboundHandlerConfig)

OutboundHandlerConfig = _reflection.GeneratedProtocolMessageType('OutboundHandlerConfig', (_message.Message,), dict(
  DESCRIPTOR = _OUTBOUNDHANDLERCONFIG,
  __module__ = 'v2ray.com.core.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.OutboundHandlerConfig)
  ))
_sym_db.RegisterMessage(OutboundHandlerConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
