# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2ray.com/core/transport/internet/headers/tls/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2ray.com/core/transport/internet/headers/tls/config.proto',
  package='v2ray.core.transport.internet.headers.tls',
  syntax='proto3',
  serialized_options=_b('\n-com.v2ray.core.transport.internet.headers.tlsP\001Z\003tls\252\002)V2Ray.Core.Transport.Internet.Headers.Tls'),
  serialized_pb=_b('\n:v2ray.com/core/transport/internet/headers/tls/config.proto\x12)v2ray.core.transport.internet.headers.tls\"\x0e\n\x0cPacketConfigBb\n-com.v2ray.core.transport.internet.headers.tlsP\x01Z\x03tls\xaa\x02)V2Ray.Core.Transport.Internet.Headers.Tlsb\x06proto3')
)




_PACKETCONFIG = _descriptor.Descriptor(
  name='PacketConfig',
  full_name='v2ray.core.transport.internet.headers.tls.PacketConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['PacketConfig'] = _PACKETCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketConfig = _reflection.GeneratedProtocolMessageType('PacketConfig', (_message.Message,), dict(
  DESCRIPTOR = _PACKETCONFIG,
  __module__ = 'v2ray.com.core.transport.internet.headers.tls.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.transport.internet.headers.tls.PacketConfig)
  ))
_sym_db.RegisterMessage(PacketConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
