# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2ray.com/core/app/stats/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2ray.com/core/app/stats/config.proto',
  package='v2ray.core.app.stats',
  syntax='proto3',
  serialized_options=_b('\n\030com.v2ray.core.app.statsP\001Z\005stats\252\002\024V2Ray.Core.App.Stats'),
  serialized_pb=_b('\n%v2ray.com/core/app/stats/config.proto\x12\x14v2ray.core.app.stats\"\x08\n\x06\x43onfigB:\n\x18\x63om.v2ray.core.app.statsP\x01Z\x05stats\xaa\x02\x14V2Ray.Core.App.Statsb\x06proto3')
)




_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='v2ray.core.app.stats.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'v2ray.com.core.app.stats.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.app.stats.Config)
  ))
_sym_db.RegisterMessage(Config)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
