# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2ray.com/core/common/net/port.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2ray.com/core/common/net/port.proto',
  package='v2ray.core.common.net',
  syntax='proto3',
  serialized_options=_b('\n\031com.v2ray.core.common.netP\001Z\003net\252\002\025V2Ray.Core.Common.Net'),
  serialized_pb=_b('\n$v2ray.com/core/common/net/port.proto\x12\x15v2ray.core.common.net\"%\n\tPortRange\x12\x0c\n\x04\x46rom\x18\x01 \x01(\r\x12\n\n\x02To\x18\x02 \x01(\rB:\n\x19\x63om.v2ray.core.common.netP\x01Z\x03net\xaa\x02\x15V2Ray.Core.Common.Netb\x06proto3')
)




_PORTRANGE = _descriptor.Descriptor(
  name='PortRange',
  full_name='v2ray.core.common.net.PortRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='From', full_name='v2ray.core.common.net.PortRange.From', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='To', full_name='v2ray.core.common.net.PortRange.To', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['PortRange'] = _PORTRANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PortRange = _reflection.GeneratedProtocolMessageType('PortRange', (_message.Message,), dict(
  DESCRIPTOR = _PORTRANGE,
  __module__ = 'v2ray.com.core.common.net.port_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.common.net.PortRange)
  ))
_sym_db.RegisterMessage(PortRange)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
