# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2ray.com/core/proxy/vmess/outbound/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v2ray.com.core.common.protocol import server_spec_pb2 as v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_server__spec__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2ray.com/core/proxy/vmess/outbound/config.proto',
  package='v2ray.core.proxy.vmess.outbound',
  syntax='proto3',
  serialized_options=_b('\n#com.v2ray.core.proxy.vmess.outboundP\001Z\010outbound\252\002\037V2Ray.Core.Proxy.Vmess.Outbound'),
  serialized_pb=_b('\n0v2ray.com/core/proxy/vmess/outbound/config.proto\x12\x1fv2ray.core.proxy.vmess.outbound\x1a\x30v2ray.com/core/common/protocol/server_spec.proto\"F\n\x06\x43onfig\x12<\n\x08Receiver\x18\x01 \x03(\x0b\x32*.v2ray.core.common.protocol.ServerEndpointBS\n#com.v2ray.core.proxy.vmess.outboundP\x01Z\x08outbound\xaa\x02\x1fV2Ray.Core.Proxy.Vmess.Outboundb\x06proto3')
  ,
  dependencies=[v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_server__spec__pb2.DESCRIPTOR,])




_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='v2ray.core.proxy.vmess.outbound.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Receiver', full_name='v2ray.core.proxy.vmess.outbound.Config.Receiver', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=205,
)

_CONFIG.fields_by_name['Receiver'].message_type = v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_server__spec__pb2._SERVERENDPOINT
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'v2ray.com.core.proxy.vmess.outbound.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.vmess.outbound.Config)
  ))
_sym_db.RegisterMessage(Config)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
