# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2ray.com/core/transport/internet/headers/noop/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2ray.com/core/transport/internet/headers/noop/config.proto',
  package='v2ray.core.transport.internet.headers.noop',
  syntax='proto3',
  serialized_options=_b('\n.com.v2ray.core.transport.internet.headers.noopP\001Z\004noop\252\002*V2Ray.Core.Transport.Internet.Headers.Noop'),
  serialized_pb=_b('\n;v2ray.com/core/transport/internet/headers/noop/config.proto\x12*v2ray.core.transport.internet.headers.noop\"\x08\n\x06\x43onfig\"\x12\n\x10\x43onnectionConfigBe\n.com.v2ray.core.transport.internet.headers.noopP\x01Z\x04noop\xaa\x02*V2Ray.Core.Transport.Internet.Headers.Noopb\x06proto3')
)




_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='v2ray.core.transport.internet.headers.noop.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=115,
)


_CONNECTIONCONFIG = _descriptor.Descriptor(
  name='ConnectionConfig',
  full_name='v2ray.core.transport.internet.headers.noop.ConnectionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['ConnectionConfig'] = _CONNECTIONCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'v2ray.com.core.transport.internet.headers.noop.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.transport.internet.headers.noop.Config)
  ))
_sym_db.RegisterMessage(Config)

ConnectionConfig = _reflection.GeneratedProtocolMessageType('ConnectionConfig', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONCONFIG,
  __module__ = 'v2ray.com.core.transport.internet.headers.noop.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.transport.internet.headers.noop.ConnectionConfig)
  ))
_sym_db.RegisterMessage(ConnectionConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
