# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2ray.com/core/transport/internet/headers/wireguard/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2ray.com/core/transport/internet/headers/wireguard/config.proto',
  package='v2ray.core.transport.internet.headers.wireguard',
  syntax='proto3',
  serialized_options=_b('\n3com.v2ray.core.transport.internet.headers.wireguardP\001Z\twireguard\252\002/V2Ray.Core.Transport.Internet.Headers.Wireguard'),
  serialized_pb=_b('\n@v2ray.com/core/transport/internet/headers/wireguard/config.proto\x12/v2ray.core.transport.internet.headers.wireguard\"\x11\n\x0fWireguardConfigBt\n3com.v2ray.core.transport.internet.headers.wireguardP\x01Z\twireguard\xaa\x02/V2Ray.Core.Transport.Internet.Headers.Wireguardb\x06proto3')
)




_WIREGUARDCONFIG = _descriptor.Descriptor(
  name='WireguardConfig',
  full_name='v2ray.core.transport.internet.headers.wireguard.WireguardConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['WireguardConfig'] = _WIREGUARDCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WireguardConfig = _reflection.GeneratedProtocolMessageType('WireguardConfig', (_message.Message,), dict(
  DESCRIPTOR = _WIREGUARDCONFIG,
  __module__ = 'v2ray.com.core.transport.internet.headers.wireguard.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.transport.internet.headers.wireguard.WireguardConfig)
  ))
_sym_db.RegisterMessage(WireguardConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
